apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: {{ include "flow.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "logging-demo.labels" . | indent 4 }}
spec:
  filters:
    - tag_normaliser: {}
    - parser:
        remove_key_name_field: true
        reserve_data: true
        parse:
          type: nginx
  match:
    - select:
        labels:
          app.kubernetes.io/name: log-generator
          app.kubernetes.io/instance: {{ .Release.Name }}
  localOutputRefs:
{{- if or .Values.file.enabled (and (not .Values.cloudwatch.enabled) (not .Values.elasticsearch.enabled) (not .Values.kafka.enabled) (not .Values.loki.enabled) (not .Values.minio.enabled) (not .Values.logdna.enabled)) }}
    - {{ include "output.fullname" . }}-file
{{- end }}
{{- if .Values.cloudwatch.enabled }}
    - {{ include "output.fullname" . }}-cloudwatch
{{- end }}
{{- if .Values.elasticsearch.enabled }}
    - {{ include "output.fullname" . }}-elasticsearch
{{- end }}
{{- if .Values.kafka.enabled }}
    - {{ include "output.fullname" . }}-kafka
{{- end }}
{{- if .Values.loki.enabled }}
    - {{ include "output.fullname" . }}-loki
{{- end }}
{{- if .Values.minio.enabled }}
    - {{ include "output.fullname" . }}-minio
{{- end }}
{{- if .Values.logdna.enabled }}
    - {{ include "output.fullname" . }}-logdna
{{- end }}

