apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: {{ include "logging-operator-logging.name" . }}
  labels:
{{ include "logging-operator-logging.labels" . | indent 4 }}
spec:
  {{- with .Values.loggingRef }}
  loggingRef: {{ . }}
  {{- end }}
  {{- with .Values.flowConfigCheckDisabled }}
  flowConfigCheckDisabled: {{ . }}
  {{- end }}
  {{- with .Values.skipInvalidResources }}
  skipInvalidResources: {{ . }}
  {{- end }}
  {{- with .Values.flowConfigOverride }}
  flowConfigOverride: {{ . }}
  {{- end }}
  {{- if and (not .Values.fluentbitDisabled) (or .Values.tls.enabled .Values.fluentbit) }}
  fluentbit:
    {{- if .Values.tls.enabled }}
    tls:
      enabled: true
      secretName: {{ .Values.tls.fluentbitSecretName | default (printf "%s-%s" (include "logging-operator-logging.name" . ) "fluentbit-tls" ) }}
      sharedKey: "{{ .Values.tls.sharedKey }}"
    {{- end }}
    {{- with .Values.fluentbit }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if and (not .Values.fluentdDisabled) (or .Values.tls.enabled .Values.fluentd) }}
  fluentd:
    {{- if .Values.tls.enabled }}
    tls:
      enabled: true
      secretName: {{ .Values.tls.fluentdSecretName | default (printf "%s-%s" (include "logging-operator-logging.name" . ) "fluentd-tls" ) }}
      sharedKey: "{{ .Values.tls.sharedKey }}"
    {{- end }}
    {{- with .Values.fluentd }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- with .Values.syslogNG }}
  syslogNG:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.defaultFlow }}
  defaultFlow:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.errorOutputRef }}
  errorOutputRef: {{ . }}
  {{- end }}
  {{- with .Values.globalFilters }}
  globalFilters:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.watchNamespaces }}
  watchNamespaces:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  clusterDomain: {{ .Values.clusterDomain }}
  controlNamespace: {{ .Values.controlNamespace | default .Release.Namespace }}
  {{- with .Values.allowClusterResourcesFromAllNamespaces }}
  allowClusterResourcesFromAllNamespaces: {{ . }}
  {{- end }}
  {{- with .Values.nodeAgents }}
  nodeAgents:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.enableRecreateWorkloadOnImmutableFieldChange }}
  enableRecreateWorkloadOnImmutableFieldChange: {{ . }}
  {{- end}}
